console.log("🔥 CONTENT FILE LOADED 🔥")
export const content = {
  hi: {
    title: "॥ सरस्वती पूजा उत्सव निमंत्रण ॥",
    shloka:
      "विद्यां ददाति विनयं, विनयाद् याति पात्रताम्।\nपात्रत्वात् धनमाप्नोति, धनाद् धर्मं ततः सुखम्॥",
    greeting: "प्रिय साथियों,",
    namaste: "आप सभी को सादर नमस्कार!",
    mainMessage:
      "इस शुभ अवसर पर, हम छात्र समिति, आपको सरस्वती पूजा के पावन पर्व के उपलक्ष्य में सादर आमंत्रित करते हैं। आइए, हम सब मिलकर विद्या की देवी माँ सरस्वती का आशीर्वाद प्राप्त करें।",
    eventDetails: "कार्यक्रम विवरण",
    date: "दिनांक: 23 जनवरी 2026 (शुक्रवार)",
    time: "समय: सुबह 10:00 बजे से (मूर्ति स्थापना एवं पूजा)",
    prasad: "प्रसाद वितरण: दोपहर 12:00 बजे",
    venue: "स्थान: फ्लैट नं. 22, नवकारधाम सोसाइटी, वाघोडिया",
    footerNote: "आपकी गरिमामयी उपस्थिति इस आयोजन की शोभा बढ़ाएगी।",
    nivedak: "निवेदक",
    nivedakName: "छात्र समिति, सरस्वती पूजा",
    contact: "संपर्क",
    financialSupport: "आर्थिक सहायता",
    financialNote: "आपकी इच्छाशक्ति अनुसार स्वीकार्य होगी।",
    upiId: "UPI ID: 9525062385-2@ibl",
    payeeName: "Saurave",
    scanToPay: "स्कैन करके भुगतान करें",
    orPayViaUpi: "या UPI से भुगतान करें",
    paymentForm: "भुगतान विवरण भरें",
    yourName: "आपका नाम",
    amount: "राशि (₹)",
    branch: "शाखा / विभाग",
    uploadScreenshot: "भुगतान का स्क्रीनशॉट अपलोड करें",
    submit: "जमा करें",
    submitting: "जमा हो रहा है...",
    thankYou: "धन्यवाद! आपका योगदान प्राप्त हुआ।",
    adminLogin: "एडमिन लॉगिन",
    password: "पासवर्ड",
    login: "लॉगिन करें",
    logout: "लॉगआउट",
    paymentRecords: "भुगतान रिकॉर्ड",
    noRecords: "कोई रिकॉर्ड नहीं",
    serialNo: "क्र.सं.",
    dateLabel: "तिथि",
    screenshot: "स्क्रीनशॉट",
    viewImage: "देखें",
    copyUpi: "UPI कॉपी करें",
    copied: "कॉपी हो गया!",
    shareWhatsApp: "WhatsApp पर साझा करें",
    copyInvitation: "निमंत्रण कॉपी करें",
    theme: "थीम",
    light: "उजला",
    dark: "अंधेरा",
    festive: "उत्सवी",
    language: "भाषा",
  },

  en: {
    title: "॥ Saraswati Puja Festival Invitation ॥",
    shloka:
      "Knowledge gives humility, from humility comes worthiness,\nFrom worthiness one gets wealth, from wealth righteousness and then happiness.",
    greeting: "Dear Friends,",
    namaste: "Warm greetings to all of you!",
    mainMessage:
      "On this auspicious occasion, we, the Student Committee, cordially invite you to celebrate the sacred festival of Saraswati Puja. Let us come together to seek the blessings of Goddess Saraswati, the deity of knowledge and wisdom.",
    eventDetails: "Event Details",
    date: "Date: January 23, 2026 (Friday)",
    time: "Time: 10:00 AM onwards (Idol Installation & Puja)",
    prasad: "Prasad Distribution: 12:00 PM",
    venue: "Venue: Flat No. 22, Navkardham Society, Waghodia",
    footerNote: "Your gracious presence will add to the glory of this celebration.",
    nivedak: "Presented by",
    nivedakName: "Student Committee, Saraswati Puja",
    contact: "Contact",
    financialSupport: "Financial Support",
    financialNote: "Contributions are welcome as per your wish.",
    upiId: "UPI ID: 9525062385-2@ibl",
    payeeName: "Saurave",
    scanToPay: "Scan to Pay",
    orPayViaUpi: "Or pay via UPI",
    paymentForm: "Fill Payment Details",
    yourName: "Your Name",
    amount: "Amount (₹)",
    branch: "Branch / Department",
    uploadScreenshot: "Upload Payment Screenshot",
    submit: "Submit",
    submitting: "Submitting...",
    thankYou: "Thank you! Your contribution has been received.",
    adminLogin: "Admin Login",
    password: "Password",
    login: "Login",
    logout: "Logout",
    paymentRecords: "Payment Records",
    noRecords: "No records found",
    serialNo: "Sr.No.",
    dateLabel: "Date",
    screenshot: "Screenshot",
    viewImage: "View",
    copyUpi: "Copy UPI",
    copied: "Copied!",
    shareWhatsApp: "Share on WhatsApp",
    copyInvitation: "Copy Invitation",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    festive: "Festive",
    language: "Language",
  },
}

export type Language = keyof typeof content
export type ContentType = typeof content.hi
